# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352070072c236e42e96667d2373035be1581a3189d4bc99784e99f435e26adbf8f62396f5df989766284a62d85fcba59accbb8d0c6468fafd0e2b02bc2175d21

test:
  secret_key_base: ce8690e8a9db448f6cd8cec7c52a46b800414c6e180e1e0422790c92e22da15ffac1f9a025511344a517ef9f8e6004f96a753670fddeebb4d8cd4e45ef6b6c20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
